using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using SignalR_Charts_Core_5_0.DataStorage;
using SignalR_Charts_Core_5_0.HubConfig;
using SignalR_Charts_Core_5_0.TimerFeature;

namespace SignalR_Charts_Core_5_0.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ChartController : ControllerBase
    {
        private readonly IHubContext<ChartHub> _hub;

        public ChartController(IHubContext<ChartHub> hub)
        {
            _hub = hub;
        }

        public IActionResult Get()
        {
            // Send out data generated by the DataManager.cs
            var timermanager = new TimerManager(() => _hub.Clients.All.SendAsync("Transferchartdata", DataManager.GetData()));
            return Ok(new { Message = "Request SignalR Completed" });
        }
    }
}